route:
  receiver: 'discord_webhook'
  repeat_interval: 4h
  group_by: [ alertname ]
  group_wait: 1s
  group_interval: 1s


receivers:
  - name: 'discord_webhook'
    webhook_configs:
      - url: 'http://discord-alerts:9094'
      # uncomment the below if you would like the
      # discord bot to send messages when an alert
      # was resolved
        # send_resolved: false
