global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'coin-api'
    static_configs:
      - targets: ['coin-api:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['coin-api-cadvisor:8080']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']


rule_files:
  - alert_rules.yml
